name: Publish

on:
  push:
    branches: [master]

concurrency:
  group: npm-publish

jobs:
  publish-test:
    uses: ./.github/workflows/pull-request.yml
    with:
      build: false

  publish-npm:
    name: NPM
    needs: [publish-test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PUSH_TOKEN }}

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: NPM
        run: npm ci

      - name: Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          extra_plugins: '@semantic-release/git'
