name: Publish

on:
  push:
    branches: [master]

jobs:
  publish-release:
    runs-on: ubuntu-latest
    concurrency:
      group: publish-release
    permissions:
      contents: write
      issues: write
      pull-requests: write
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      pr: ${{ steps.release.outputs.pr }}
    steps:
      - uses: googleapis/release-please-action@v5
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  publish-test:
    needs: [publish-release]
    if: needs.publish-release.outputs.pr && !needs.publish-release.outputs.release_created
    uses: ./.github/workflows/test.yml
    with:
      ref: ${{ needs.publish-release.outputs.pr.headBranchName }}

  publish-npm:
    needs: [publish-release]
    if: needs.publish-release.outputs.release_created
    runs-on: ubuntu-latest
    environment: npm
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
      - run: npm ci
      - run: npm run build
      - run: npm publish --provenance --access public
