name: Publish

on:
  push:
    branches: [master]

concurrency:
  group: npm-publish

jobs:
  publish-test:
    uses: ./.github/workflows/test.yml

  publish-npm:
    name: NPM
    needs: [publish-test]
    runs-on: ubuntu-latest
    environment: npm
    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.PUSH_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - run: npm ci

      - run: npm run build

      - uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          extra_plugins: '@semantic-release/git'
