name: Pull Request

on:
  pull_request:

  workflow_call:
    inputs:
      build:
        description: Should it test by building?
        required: false
        default: true
        type: boolean

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22, 24]

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: NPM
        run: npm ci

      - name: Test
        run: npx tsc --noEmit && npm test
