name: Test

on:
  workflow_call:
    inputs:
      ref:
        required: false
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22, 24]
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.ref || '' }}
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npx tsc --noEmit && npm test
